name: build & publish Docker image

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    uses: './.github/workflows/lint.yml'

  validate:
    name: validate
    uses: './.github/workflows/validate.yml'

  build-publish:
    needs:
      - lint
      - validate
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: log into the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: build and push dagster-pipeline Docker image
      uses: docker/build-push-action@v4
      with:
        file: pipeline.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dagster-pipeline:latest
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: build and push dagster-daemon Docker image
      uses: docker/build-push-action@v4
      with:
        file: dagster.Dockerfile
        target: daemon
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dagster-daemon:latest
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: build and push dagster-dagit Docker image
      uses: docker/build-push-action@v4
      with:
        file: dagster.Dockerfile
        target: dagit
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dagster-dagit:latest
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
