name: build & publish preview Docker image from Git tag

on:
  push:
    tags:
      - 'preview/**'

jobs:
  lint:
    name: lint
    uses: './.github/workflows/lint.yml'

  validate:
    name: validate
    uses: './.github/workflows/validate.yml'

  build-publish:
    needs:
      - lint
      - validate
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: log into the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: determine Docker images tag
      run: |
        set -x # todo: remove
        echo "DOCKER_TAG=$(cut -d'/' -f2- <<<'${{ github.ref_name }}')" >> $GITHUB_ENV

    # todo: DRY with build-publish.yml workflow
    - name: build and push dagster-pipeline Docker image
      uses: docker/build-push-action@v6
      with:
        file: pipeline.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dagster-pipeline:${{ env.DOCKER_TAG }}
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: build and push dagster-daemon Docker image
      uses: docker/build-push-action@v6
      with:
        file: dagster.Dockerfile
        target: daemon
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dagster-daemon:${{ env.DOCKER_TAG }}
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: build and push dagster-dagit Docker image
      uses: docker/build-push-action@v6
      with:
        file: dagster.Dockerfile
        target: dagit
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dagster-dagit:${{ env.DOCKER_TAG }}
        platforms: linux/amd64,linux/arm64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
