name: lint

on:
  push:
    branches:
      - '*'

  # make workflow "callable" by others
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: python:3.12

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Python v${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: pip install
      run: pip install -r requirements-dagster.txt -r requirements-dev.txt

    - name: lint using ruff
      run: ruff check --output-format=github .

    - name: format using ruff
      run: ruff format --check .

    - name: type-check using mypy
      run: mypy .
